### ISSUE TITLE
A bug on HScore computation 

### ISSUE THREAD

**Issue by l903404160** [VisionLearningGroup/OVANet#1]
After run the scripts I found that there is a bug when computing the HScore.

In detail, the [open_class](https://github.com/VisionLearningGroup/OVANet/blob/211114469346db0e0df4079ec78439b81e528dde/eval.py#L108) is defined as a extra class with a predefined classifier. So it should be **15** when one wants to use the UniDA setting of OfficeHome (10/5/50). But the [known_acc](https://github.com/VisionLearningGroup/OVANet/blob/211114469346db0e0df4079ec78439b81e528dde/eval.py#L169) is produced with `known_acc = per_class_acc[:open_class - 1].mean()`.
The problem is `known_acc` will equals to 'acc_close_all' when source private classes existed in UniDA setting. So HScore is acquired with the wrong `known_acc`. 

I run an experiment and I give the result here. The experiment is performed on OfficeHome - Art2Clipart (10/5/50). I haven't changed any parameters at all.
```
['step 10000', 'closed perclass', [0.8, 0.16071428571428573, 0.296875, 0.15306122448979592, 0.898989898989899, 0.40404040404040403, 0.4931506849315068, 0.9130434782608695, 0.2948717948717949, 0.3333333333333333, 0.8319482917820868], 'acc per class 0.5072753087649069', 'acc 76.02586421288237', 'acc close all 65.41450777202073', 'h score 0.6302559578815994', 'roc 0.7201107714290726', 'roc ent 0.7298303822459522', 'roc softmax 0.721641334041403', 'best hscore 0.6167971843264333', 'best thr 0.8421052631578947']
```
Correct HScore is **0.6046**
HScore in log is **h score 0.6302559578815994**
If I change to use the `acc_close_all` as the accuracy of common label set, I got the HScore reported in the log. 

I'm looking forward the final result of VisDA2021. Thank you for your contribution.  :smile:

**Comment by ksaito-ut** [comment]
Hi, thanks for pointing out the issue! 

I looked into the issue and found that the line below needs to replace `known_acc`.
` known_acc = per_class_acc[:len(class_list)-1].mean()`

I think `acc_close_all` is the accuracy evaluated on known samples without any rejection, which is not appropriate to use to compute Hscore. Thanks for sharing the issue and let us know if you think this is still a problem.
