### ISSUE TITLE
How to report the results

### ISSUE THREAD

**Issue by zhaoxin94** [VisionLearningGroup/OVANet#3]
Hi, thank you very much for open-sourcing such a wonderful work!

I have some questions aobut how to report the results.

(1)  I should choose the result of the last step, or the best result across all steps?
(2)  In addition, did you repeat the experiments several times and report the mean results?

I just want to known some details, so I can do further research based on your wonderful work.

**Comment by donggoing** [comment]
> Hi, thank you very much for open-sourcing such a wonderful work!
> 
> I have some questions aobut how to report the results.
> 
> (1) I should choose the result of the last step, or the best result across all steps? (2) In addition, did you repeat the experiments several times and report the mean results?
> 
> I just want to known some details, so I can do further research based on your wonderful work.

请问您得到解答了吗？
